musicform-web-app/musicapp/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('musicform.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musicform-web-app/musicform/urls.py
from django.conf.urls import url
from .views import band_view
from .views import profile_view
from .views import home_view

from .views.home_view import TemplateView
from .views.profile_view import LogoutDetail, ProfileDetail, AllSongsDetail

from django.utils.functional import curry
from django.views.defaults import *

urlpatterns = [
    # Registration URLs
    url(r'^register/$', profile_view.register, name='register'),
    # Login URLs
    url(r'^login/$', profile_view.login_form, name='login'),
    url(r'^logout/$', LogoutDetail.as_view(), name='logout'),
    # Band URLs
    url(r'^band/new/$', band_view.band_new, name='band_new'),
    url(r'^ajax/validate_bandname/$', band_view.validate_bandname, name='validate_bandname'),
    url(r'^band/(?P<band_id>[0-9]+)/edit/$', band_view.edit_band, name='edit_band'),
    url(r'^band/(?P<band_id>[0-9]+)/$', band_view.band_information, name='band_information'),
    url(r'^band/(?P<pk>[0-9]+)/edit_comment/$', band_view.edit_comment, name='edit_comment'),
    url(r'^band/(?P<pk>[0-9]+)/remove_comment/$', band_view.remove_comment, name='remove_comment'),
    url(r'^band/(?P<band_id>[0-9]+)/request/$', band_view.user_request, name='user_request'),
    url(r'^band/(?P<pk>[0-9]+)/approve_request/$', band_view.approve_request, name='approve_request'),
    url(r'^band/(?P<pk>[0-9]+)/decline_request/$', band_view.decline_request, name='decline_request'),
    # url(r'^band/request$', band_view.request, name='brequest'),
    url(r'^band/view_request/$', band_view.manage_request, name='manage_request'),
    # Navigation URLs
    url(r'^$', TemplateView.as_view(), name='home'),
    url(r'^status/$', band_view.status, name='status'),
    url(r'^request/$', band_view.request, name='request'),
    url(r'^search/$', home_view.search, name='search'),
    url(r'^about/$', TemplateView.as_view(template_name="musicform/about.html"), name='about'),
    url(r'^how_to/$', TemplateView.as_view(template_name="musicform/how_to.html"), name='how_to'),
    # Profile URLs
    url(r'^profile/$', ProfileDetail.as_view(), name='profile'),
    url(r'^profile/(?P<prof_id>[0-9]+)/$', profile_view.view_other_prof, name='view_profile'),
    url(r'^profile/edit_profile/$', profile_view.edit_profile, name='edit_profile'),
    url(r'^ajax/validate_username/$', profile_view.validate_username, name='validate_username'),
    url(r'^profile/genre/$', profile_view.user_genre, name='user_genre'),
    url(r'^profile/song/$', profile_view.user_song, name='user_song'),
    url(r'^profile/all_songs/$', AllSongsDetail.as_view(), name='all_songs'),
    url(r'^profile/song/([0-9]+)/$', profile_view.song_information, name='song_information'),
    url(r'^profile/instruments/$', profile_view.user_instruments, name='user_instruments'),
]

handler500 = curry(server_error, template_name='musicform/admin/500.html')
handler404 = curry(page_not_found, template_name='musicform/admin/404.html')
handler403 = curry(permission_denied, template_name='musicform/admin/403.html')

musicform-web-app/musicform/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from datetime import datetime

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="userprofile")

    join_date = models.DateTimeField(
        default=timezone.now
    )
    biography = models.TextField()
    birth_date = models.DateTimeField(
        default=timezone.now
    )
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    LOCATION_CHOICES = (
        ('Sydney', 'Sydney'),
        ('Canberra', 'Canberra'),
        ('Brisbane', 'Brisbane'),
        ('Melbourne', 'Melbourne'),
        ('Tasmania', 'Tasmania'),
        ('Darwin', 'Darwin'),
        ('Adelaide', 'Adelaide'),
        ('Perth', 'Perth'),
    )
    PROFILE_ICONS = (
        ('bells.png', 'Bell'),
        ('cloud.png', 'Cloud'),
        ('disc.png', 'Disc'),
        ('drum.png', 'Drums'),
        ('eq.png', 'Equaliser'),
        ('guitar.png', 'Guitar'),
        ('mic.png', 'Microphone'),
        ('piano.png', 'Piano'),
        ('sound.png', 'Sound'),
        ('soundboard.png', 'Soundboard'),
        ('tape.png', 'Tape'),
        ('tape2.png', 'Radio'),
        ('violin.png', 'Violin'),
        ('xylo.png', 'Xylophone'),
    )
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES)
    location = models.CharField(max_length=50, choices=LOCATION_CHOICES)
    profile_icon = models.FileField(choices=PROFILE_ICONS, default="bells")
    mobile_number = models.CharField(max_length=12)

    def __unicode__(self):
        return self.user.username


class Requests(models.Model):
    id = models.IntegerField(primary_key=True)
    user_id_from = models.ForeignKey('auth.User', related_name='sender')
    user_id_to = models.ForeignKey('auth.User', related_name='recipient')
    band = models.ForeignKey('musicform.Band', related_name='request', blank=False, null=True)
    text = models.TextField()
    approved = models.BooleanField(default=False)
    hide_function = models.BooleanField(default=False)
    date_created = models.DateTimeField(
        default=timezone.now
    )
    status = models.IntegerField(default=0)

    class Meta:
        unique_together = ('user_id_from', 'user_id_to', 'band',)

    def approve(self):
        self.approved = True
        self.hide_function = True
        self.save()

    def __str__(self):
        return self.text


class Song(models.Model):
    id = models.IntegerField(primary_key=True)
    uploader = models.ForeignKey('auth.User')
    filename = models.CharField(max_length=50)
    song_name = models.CharField(max_length=50)
    file = models.FileField()
    upload_date = models.DateTimeField(
        default=timezone.now
    )

    def get_absolute_url(self):
        return reverse('musicform:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.song_name


class Band(models.Model):
    id = models.IntegerField(primary_key=True)
    creator = models.ForeignKey('auth.User')
    name = models.CharField(max_length=30)
    location = models.CharField(max_length=50, default="Sydney")
    date_created = models.DateTimeField(
        default=timezone.now
    )
    introduction = models.CharField(max_length=1000)
    members = models.IntegerField(default=0)
    logo = models.FileField(blank=True)

    def get_absolute_url(self):
        return reverse('musicform:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    def approved_members(self):
        return self.request.filter(approved=True)


class BandMembers(models.Model):
    id = models.IntegerField(primary_key=True)
    band = models.ForeignKey('musicform.Band', related_name='member', blank=False, null=True)
    author = models.ForeignKey('auth.User')

    def approve(self):
        self.save()


class BandComments(models.Model):
    id = models.IntegerField(primary_key=True)
    band = models.ForeignKey('musicform.Band', related_name='comments', blank=False, null=True)
    author = models.ForeignKey('auth.User')
    text = models.TextField()
    created_date = models.DateTimeField(
        default=timezone.now
    )
    updated_date = models.DateTimeField(
        default=timezone.now
    )
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.save()

    def __str__(self):
        return self.text


class Instrument(models.Model):
    id = models.IntegerField(primary_key=True)
    owner = models.ForeignKey('auth.User')
    instrument = models.CharField(max_length=100)
    grade = models.IntegerField()

    def __str__(self):
        return self.instrument

    def get_absolute_url(self):
        return reverse('musicform:profile', kwargs={'pk': self.pk})

    class Meta:
        unique_together = ('owner', 'instrument')


class Genre(models.Model):
    GENRE_CHOICES = (
        ('Alternative', 'Alternative'),
        ('Classical', 'Classical'),
        ('Country', 'Country'),
        ('Electronic', 'Electronic'),
        ('Hip-Hop', 'Hip-Hop'),
        ('Rap', 'Rap'),
        ('Indie', 'Indie'),
        ('Jazz', 'Jazz'),
        ('Pop', 'Pop'),
        ('Soul', 'Soul'),
        ('Rock', 'Rock')
    )
    # id = models.IntegerField(primary_key=True)
    owner = models.ForeignKey('auth.User')
    genre = models.CharField(max_length=100, choices=GENRE_CHOICES)

    class Meta:
        unique_together = ('owner', 'genre',)

    def __str__(self):
        return self.genre

musicform-web-app/musicform/views/band_view.py
from django.shortcuts import render, get_object_or_404, render_to_response, redirect

from django.http import HttpResponseRedirect, HttpResponseNotFound, Http404, HttpResponse
from django.http import JsonResponse

from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.db import models
from django.db.models import Q
from django.template import RequestContext
from django.utils import timezone

from django.views import generic
from django.views.generic import CreateView, View

from django.urls import reverse

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import IntegrityError

from ..models import Band, BandComments, Song, Instrument, Genre, Requests, UserProfile
from ..forms import UserForm, UserProfileForm, BandForm, CommentForm, SongForm, InstrumentForm, GenreForm, RequestForm

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']
SONG_FILE_TYPES = ['mp3', 'wav']


@login_required
def band_new(request):
    """
    The code below will help create a new band,
    firstly checking if the user is logged in first, and
    another check to distinguish whether the user is actually authorised.

    The band will then update the fields which relate to the model of 'Band'
    This includes the file being chosen and the creator which relates to the user
    that requested.

    If the form sent is valid, the information will then send the information to the
    database.
    """
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        form = BandForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            band = form.save(commit=False)
            band.published_date = timezone.now()
            band.logo = request.FILES['logo']
            band.creator = request.user
            band.location = request.user.userprofile.location
            file_type = band.logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'band': band,
                    'error_message': 'Invalid Image Type',
                }
                return render(request, 'musicform/band/new_band.html', context)
            band.save()
            return HttpResponseRedirect('/status/')
        context = {
            "form": form
        }
        return render(request, 'musicform/band/new_band.html', context)


@login_required
def band_information(request, band_id):
    """
    This will pull the information from a band with the associated
    primary key.

    Using the method of 'get_object_or_404' will handle if the information
    provided will raise a 404 error. Otherwise it will get information of that
    current band.

    The fields within the context variable will include a user and a band,
    which will allow the template within the render to get the appropriate information
    """
    user = request.user
    band = get_object_or_404(Band, pk=band_id)

    comment_form = CommentForm(request.POST or None)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.author = request.user
        comment.band = band
        comment.save()

    context = {
        'user': user,
        'band': band,
        'comment_form': comment_form,
    }
    return render(request, 'musicform/band/band_information.html', context)


@login_required
def edit_band(request, band_id):
    """
    The edit functions:

    This function is similar to creating a band, but instead using the keyword
    'instance' will get the information from the primary key and pull all the
    appropriate information about the given model.
    """
    band = get_object_or_404(Band, pk=band_id)
    if request.method == "POST":
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            band = form.save(commit=False)
            band.creator = request.user
            band.published_date = timezone.now()
            band.save()
            return HttpResponseRedirect(reverse('band_information', args=(band.id,)))
    else:
        form = BandForm(instance=band)
    return render(request, 'musicform/band/edit_band.html', {'form': form})


@login_required
def edit_comment(request, pk):
    """
    The edit functions:

    This function is similar to creating a comment, but instead using the keyword
    'instance' will enable to get the information from the primary key and pull all the
    appropriate information about the given model.
    """
    comment = get_object_or_404(BandComments, pk=pk)
    band_pk = comment.band.pk
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.updated_date = timezone.now()
            comment.save()
            return HttpResponseRedirect(reverse('band_information', args=(band_pk,)))
    else:
        form = CommentForm(instance=comment)
    return render(request, 'musicform/band/edit_comment.html', {'form': form})




@login_required
def remove_comment(request, pk):
    """
    The remove functions:

    Remove the given comment provided by a primary key
    """
    comment = get_object_or_404(BandComments, pk=pk)
    band_pk = comment.band.pk
    comment.delete()
    return HttpResponseRedirect(reverse('band_information', args=(band_pk,)))


@login_required
def status(request):
    """
    This function retrieves all bands in the given function
    """
    context = {
        'bands': Band.objects.all()
    }
    return render(request, 'musicform/status.html', context)


@login_required
def request(request):
    band_request = Requests.objects.filter(user_id_from=request.user,
                                           hide_function='False')
    context = {
        'requests': band_request
    }
    return render(request, 'musicform/request.html', context)


def user_request(request, band_id):
    form = RequestForm(request.POST or None)
    band = get_object_or_404(Band, pk=band_id)
    if form.is_valid():
        band_request = form.save(commit=False)
        band_request.user_id_from = request.user
        band_request.user_id_to = band.creator
        band_request.band = band
        try:
            band_request.save()
        except IntegrityError:
            context = {
                'form': form,
                'error': 'Sorry, already requested.'
            }
            return render(request, 'musicform/profile/new_request.html', context)
        return HttpResponseRedirect('/request/')
    context = {
        'form': form
    }
    return render(request, 'musicform/profile/new_request.html', context)

@login_required
def manage_request(request):
    context = {
        'requests': Requests.objects.filter(user_id_to=request.user,
                                            hide_function='False')
    }
    return render(request, 'musicform/request.html', context)


def approve_request(request, pk):
    band_request = get_object_or_404(Requests, pk=pk)
    band_request.approve()
    return redirect('band_information', band_id=band_request.band.id)


def decline_request(request, pk):
    band_request = get_object_or_404(Requests, pk=pk)
    band_pk = band_request.band.pk
    band_request.delete()
    return redirect('band_information', band_id=band_pk)


'''
AJAX functions to fulfill the specifications
'''


def get_current_weather(request):
    """
    Provided with a string regarding the location, pull the current weather data
    """
    return 1


def like_band(request):
    """
    Provided with a primary key of a band, allow the user to like a band
    """
    return 1


def favourite_band(request):
    """
    Provided with a primary key of a band, allow the user to favourite a band
    """
    return 1


def validate_bandname(request):
    band_name = request.GET.get('band_name', None)
    if band_name is None:
        return HttpResponse(status=400)
    data = {
        'is_taken': Band.objects.filter(name__iexact=band_name).exists()
    }
    return JsonResponse(data)


def validate_request(request):
    band_requester = request.GET.get('band_requester', None)
    band_owner = request.GET.get('band_owner', None)
    if band_requester is None:
        return HttpResponse(status=400)
    data = {
        'already_member': Requests.objects.filter(user_id_to=band_requester).filter(user_id_from=band_owner).exists()
    }
    return JsonResponse(data)

musicform-web-app/musicform/templates/musicform/profile/all_songs.html
{% extends "musicform/base.html" %}

{% block title %}
    Song
{% endblock %}

{% block content %}

    {% for song in songs %}
        <h1>{{ song.song_name }}</h1>

        <br>

        <audio controls>
            <source src="{{ song.file.url }}" type="audio/mpeg">

        </audio>
    {% endfor %}

{% endblock %}

musicform-web-app/musicform/templates/musicform/profile/edit_profile.html
{% extends 'musicform/base.html' %}

{% block content %}
    <h1>Update Profile</h1>
    <div class="well">
        <form id="user_form" method="POST" class="post-form" action="/register/" enctype="multipart/form-data">

            {% csrf_token %}

            <div class="login-box1">
                <div>
                    <h4>
                        Username {{ user_form.username }}
                    </h4>
                </div>
                <div>
                    <h4>First Name {{ user_form.first_name }}
                    </h4>
                </div>
                <div>
                    <h4>
                        Last Name {{ user_form.last_name }}
                    </h4>
                </div>

                <div>
                    <h4>
                        E-mail {{ user_form.email }}
                    </h4>
                </div>

                <div>
                    <h4>Password
                        <fieldset disabled="disabled">
                            {{ user_form.password }}
                        </fieldset>
                    </h4>
                </div>
                <div>
                    <h4>Biography
                        {{ profile_form.biography }}
                    </h4>
                </div>

                <div>
                    <h4>Birth Date
                        {{ profile_form.birth_date }}
                    </h4>
                </div>
                <div>
                    <h4>Gender&nbsp&nbsp&nbsp&nbsp
                        {{ profile_form.gender }}
                    </h4>
                </div>
                <div>
                    <h4>
                        Location&nbsp&nbsp&nbsp&nbsp
                        {{ profile_form.location }}
                    </h4>
                </div>
                <div>

                    <h4>Mobile&nbsp&nbsp&nbsp&nbsp&nbsp
                        {{ profile_form.mobile_number }}
                </div>

                <div>
                    <h4>Profile Icon
                        {{ profile_form.profile_icon }}
                </div>
                <div>
                    <button type="register" class="save btn btn-success">
                        Update Profile
                    </button>
                </div>
        </form>
    </div>
{% endblock %}

musicform-web-app/musicform/templates/musicform/profile/new_genre.html
{% extends "musicform/base.html" %}

{% block title %}
    New Song
{% endblock %}

{% block content %}

    {% if error %}
        {{ error }}
    {% endif %}

    <form method="POST" class="post-form" role="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="well">
            {{ genre_form.as_p }}

            <button type="submit" class="save btn btn-info">
                Submit
            </button>
        </div>
    </form>


{% endblock %}

musicform-web-app/musicform/templates/musicform/profile/new_instrument.html
{% extends "musicform/base.html" %}

{% block title %}
    New Instrument
{% endblock %}

{% block content %}

    <div class="well">
        {% if error %}
            {{ error }}
        {% endif %}
        <form method="POST" class="post-form" role="form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group" action="{% url 'login' %}">
                <label class="control-label col-sm-2" for="id_username">
                    Instrument:
                </label>
                <div class="col-sm-10">
                    <input id="id_name" maxlength="30" name="instrument" type="text" placeholder="Instrument Name" required>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2">
                    Grade:
                </label>
                <div class="col-sm-10">
                    <select name="grade">
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                        <option value="4">Four</option>
                        <option value="5">Five</option>
                        <option value="6">Six</option>
                        <option value="7">Seven</option>
                    </select>
                </div>
            </div>

            <br>

            <button type="submit" class="save btn btn-info">
                Submit
            </button>
        </form>
    </div>


{% endblock %}

musicform-web-app/musicform/templates/musicform/profile/new_request.html
{% extends "musicform/base.html" %}

{% block title %}
    New Request
{% endblock %}

{% block content %}


    <div class="well">

        <h1> Request </h1>
        {% if error %}
            {{ error }}
        {% endif %}
        <form method="POST" class="post-form" role="form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group" action="{% url 'login' %}">
                <label class="control-label col-sm-2" for="id_username">
                    Message:
                </label>
                <div class="col-sm-10">
                <textarea id="id_introduction" name="text" type="url" required
                          rows="4" cols="50" maxlength="1000" placeholder="Send a message to the band manager"></textarea>
                </div>
            </div>

            <button type="submit" class="save btn btn-info">
                Submit
            </button>
        </form>
    </div>


{% endblock %}

musicform-web-app/musicform/templates/musicform/profile/new_song.html
{% extends "musicform/base.html" %}

{% block title %}
    New Song
{% endblock %}

{% block content %}


    <div class="well">
        <form method="POST" class="post-form" role="form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group" action="{% url 'login' %}">
                <label class="control-label col-sm-2" for="id_username">
                    Song Name:
                </label>
                <div class="col-sm-10">
                    <input id="id_name" maxlength="30" name="song_name" type="text" placeholder="Song Name" required>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2">
                    Song File:
                </label>
                <div class="col-sm-10">
                    <input maxlength="30" name="file" type="file" required>
                </div>
            </div>

            <button type="submit" class="save btn btn-info">
                Submit
            </button>
        </form>
    </div>


{% endblock %}

musicform-web-app/musicform/templates/musicform/profile/search_user.html
{% extends "musicform/base.html" %}

{% block title %}
    Status
{% endblock %}

{% block content %}
    <style type="text/css">
        body {
            background-image:url(/static/images/status.jpg);
            background-attachment:fixed;
            background-size: cover;
            font-family: 'Open Sans', sans-serif;
            color:#ffffff;
        }
    </style>
    <title>Status</title>
    <!-- Page Heading -->

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Musicians
                <a href="{% url 'search' %}" type="submit" class="save btn btn-primary pull-right">
                    Back to Search
                </a>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    {% if users %}
        {% for user in users %}
            <!-- Project One -->
            <div class="row">
                <div class="col-md-7">
                    <a href="{% url 'view_profile' user.id %}">
                        <img class="img-responsive"
                             src="/static/images/icons/profile_icons/{{ user.userprofile.profile_icon }}"
                             alt="" height="150" width="300">
                    </a>
                </div>
                <div class="col-md-5">
                    <h3>{{ user.username }}</h3>
                    <h4> <b>Located At:</b> {{ user.userprofile.location }}</h4>
                    <br>
                    <a class="btn btn-success pull-right" href="{% url 'view_profile' user.id %}">
                        View Profile <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>
            </div>
            <!-- /.row -->

            <hr>
        {% endfor %}
    {% else %}

        <div class="jumbotron" style="color:#000000;">
            <h3>No musicians matched your search.</h3>
        </div>

    {% endif %}

{% endblock %}

musicform-web-app/musicform/templates/musicform/profile/song.html
{% extends "musicform/base.html" %}

{% block title %}
    Song
{% endblock %}

{% block content %}

    <h1>{{ song.song_name }}</h1>

    <audio controls>
        <source src="{{ song.file.url }}" type="audio/mpeg" preload="auto">

    </audio>

{% endblock %}